// <auto-generated />
using System;
using Infrastructure.Ef;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    partial class ProductDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ApplicationCore.Entity.Product", b =>
                {
                    b.Property<long>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProductId"), 1L, 1);

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,0)");

                    b.Property<long>("ProcuctCategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProductDescription")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Name");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("ProductId");

                    b.HasIndex("ProcuctCategoryId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = 1L,
                            Price = 2000m,
                            ProcuctCategoryId = 1L,
                            ProductName = "C#の本",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            ProductId = 2L,
                            Price = 2200m,
                            ProcuctCategoryId = 1L,
                            ProductName = "Visual Studioの本",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            ProductId = 3L,
                            Price = 2500m,
                            ProcuctCategoryId = 1L,
                            ProductName = ".NETの本",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            ProductId = 4L,
                            Price = 150000m,
                            ProcuctCategoryId = 2L,
                            ProductName = "冷蔵庫",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            ProductId = 5L,
                            Price = 280m,
                            ProcuctCategoryId = 3L,
                            ProductName = "トランプ",
                            RowVersion = new byte[0]
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entity.ProductCategory", b =>
                {
                    b.Property<long>("ProductCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProductCategoryId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("ProductCategoryId");

                    b.ToTable("ProductCategories", (string)null);

                    b.HasData(
                        new
                        {
                            ProductCategoryId = 1L,
                            Name = "本",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            ProductCategoryId = 2L,
                            Name = "家電",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            ProductCategoryId = 3L,
                            Name = "おもちゃ",
                            RowVersion = new byte[0]
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entity.Product", b =>
                {
                    b.HasOne("ApplicationCore.Entity.ProductCategory", "ProductCategory")
                        .WithMany("Products")
                        .HasForeignKey("ProcuctCategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_Products_ProductCategories");

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("ApplicationCore.Entity.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
